// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetTimerStatus() {
  return window['go']['main']['App']['GetTimerStatus']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function SaveNote(arg1, arg2) {
  return window['go']['main']['App']['SaveNote'](arg1, arg2);
}

export function StartTaskTimer(arg1) {
  return window['go']['main']['App']['StartTaskTimer'](arg1);
}

export function StopTimer() {
  return window['go']['main']['App']['StopTimer']();
}

export function SwitchTaskTimer(arg1) {
  return window['go']['main']['App']['SwitchTaskTimer'](arg1);
}
