// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetTimerStatus():Promise<Record<string, any>>;

export function Greet(arg1:string):Promise<string>;

export function SaveNote(arg1:string,arg2:string):Promise<string>;

export function StartTaskTimer(arg1:string):Promise<void>;

export function StopTimer():Promise<void>;

export function SwitchTaskTimer(arg1:string):Promise<boolean>;
